'use server'
import { RowDataPacket,ResultSetHeader } from 'mysql2/promise';

import pool from '../conn';
import { timeStampGen } from '@/lib/helpers';

export const updateDailyStats = async (userId: number, daily_field: number | undefined, note: string): Promise<boolean>  => {
    const poolConn = await pool.getConnection();
    try {

        const now = new Date();
        const query = `
            UPDATE \`user-daily-stats\`
            SET finished = 'yes', note = ?, completed_at = ?
            WHERE user_id = ? AND id = ? 
        `
        const [rows] = await poolConn.query<ResultSetHeader>(query, [note, now, userId, daily_field]);
        if (rows.affectedRows > 0) {
            return true
        }

        return false;

    } catch (error) {
        console.error(`${timeStampGen()} Error generated by func updateDailyStats: ${error}`);
        return false;
    } finally {
        poolConn.release();
    };
}